version: 2

workflows:
  version: 2
  main:
    jobs:
      - hold:
          type: approval
      - build:
          requires: [hold]

jobs:
  build:
    requires: hold
    # Specify the Xcode version to use
    macos:
      xcode: "10.1.0"

    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 7
            SCAN_SCHEME: SimplePagedViewFrameworkTests
            SCAN_DERIVED_DATA_PATH: build/DerivedData
            SCAN_OUTPUT_DIRECTORY: build/Output

      - persist_to_workspace:
          root: .
          paths:
            - 'build'

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
        
